### ISSUE TITLE
Add tests similar to cookiecutter-invenio-module

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/cookiecutter-invenio-instance#14]

**Comment by slint** [comment]
Ideally what we need is a proper test matrix for all the possible combinations of cookiecutter parameters that actually have a impact on the underlying services, ie. `database` and `elasticsearch`. 

This involves setting up a bit of duplicate travis.yml configuration in order to satisfy all possible environments, basically a combination of [`invenio-db`](https://github.com/inveniosoftware/invenio-db/blob/b3c03263b7e891ee060f97e5860d3e492331bad7/.travis.yml#L19-L21) and [`invenio-search`](https://github.com/inveniosoftware/invenio-search/blob/a246c84809d9c3a136723cad3733404fe747ce50/.travis.yml#L31-L32).

**Comment by switowski** [comment]
I have a WIP for E2E tests, I can also add both versions of the DB and ES there:
https://github.com/switowski/cookiecutter-invenio-instance/blob/2018-05-16-e2e-tests/.travis.yml

**Comment by switowski** [comment]
Actually, that would require changing the `run-tests.sh` to cookie-cut with different parameters, so maybe it's better to start another PR for that.

**Comment by lnielsen** [comment]
Fixed in 1bee0fb02e983f80191d87d8ebde7bf74eae61d6
