### ISSUE TITLE
RFC: Python 3 only support in template

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/cookiecutter-invenio-instance#24]
Should we remove Python 2 support from the cookiecutter template in order to not encourage starting new projects on Python 2.

**Comment by egabancho** [comment]
Perhaps put Python 3 as default (and document why you should use it), but keep Python 2, specially because some of our own services will need it as we depend on some libraries that are not Python 3 compatible, i.e. xrootd python bindings.

After all Python 2.7 will go away in 2020 https://pythonclock.org/ 😜

**Comment by egabancho** [comment]
I wonder now were I was looking to write my comment 🤦
